### ISSUE TITLE
License

### ISSUE THREAD

**Issue by buxel** [trondhindenes/PowershellModules#1]
Hello @trondhindenes ,
i'd love to use your modules in my current project but sadly i cannot find any licensing information, which i'am required to check. Could you state your lincensing somewhere in this repo so i get a chance to use them? 

Thank you.

**Comment by trondhindenes** [comment]
Hi, 
Sure, I'll add some licensing info today.

**Comment by trondhindenes** [comment]
Added MIT license.

**Comment by buxel** [comment]
Thanks, much appreciated.
